### ISSUE TITLE
大文件处理

### ISSUE THREAD

**Issue by mintzhao** [cooladdr/dirtreehash#1]
### 描述

未进行大文件处理

```
func getHash(file string) []byte {
    f, err := os.Open(file)
    if err != nil {
        fmt.Printf("Open:%s error", file)
        panic(err)
    }
    defer f.Close()

    h := sha1.New()
    _, err = io.Copy(h, f)
    if err != nil {
        panic(err)
    }

    return h.Sum(nil)
}
```

**Comment by cooladdr** [comment]
标准库里已经考虑了大文件问题，当没有分配buffer时，其实现方法里会创建一个32_1024的buffer ，以下代码是从标准库里拷贝出来的
if buf == nil {     buf = make([]byte, 32_1024) }
由于我以前基本上没有用到过sha1，不知道您说的是不是这个问题，如果不是，希望继续issue我，谢谢！

func Copy(dst Writer, src Reader) (written int64, err error) {
    return copyBuffer(dst, src, nil)
}
func copyBuffer(dst Writer, src Reader, buf []byte) (written int64, err error) {
    // If the reader has a WriteTo method, use it to do the copy.
    // Avoids an allocation and a copy.
    if wt, ok := src.(WriterTo); ok {
        return wt.WriteTo(dst)
    }
    // Similarly, if the writer has a ReadFrom method, use it to do the copy.
    if rt, ok := dst.(ReaderFrom); ok {
        return rt.ReadFrom(src)
    }
    if buf == nil {
        buf = make([]byte, 32*1024)
    }
    for {
        nr, er := src.Read(buf)
        if nr > 0 {
            nw, ew := dst.Write(buf[0:nr])
            if nw > 0 {
                written += int64(nw)
            }
            if ew != nil {
                err = ew
                break
            }
            if nr != nw {
                err = ErrShortWrite
                break
            }
        }
        if er == EOF {
            break
        }
        if er != nil {
            err = er
            break
        }
    }
    return written, err
}

**Comment by mintzhao** [comment]
标准库里是每次读32m的数据，但是读完的数据还是放到了dst的这个对象里，无论怎么读，最后的数据都是累加起来的

**Comment by cooladdr** [comment]
h := sha1.New()
    _, err = io.Copy(h, f)
dst不就是传进去的sha1对象吗？

**Comment by mintzhao** [comment]
没理解？比如我有个10g的文件，但只有5g内存。你能通过io.Copy()直接把数据全部读出来么？
你通过io.Copy(h,f)把数据读到h中了，但是之前的f能保存10g大小的文件么？

**Comment by cooladdr** [comment]
mintzhao能不能留个联系方式，加我QQ也行258468201，我看io.Copy(h,f)的内部实现是一次从f中读取数据到32M的buf中，然后写到h里，一直这样循环到读完f的数据；我没看出问题来（_—_）

**Comment by mintzhao** [comment]
没有问题
